### ISSUE TITLE
Issues with first setup with Foundry v0.6.5

### ISSUE THREAD

**Issue by RyanLiu6** [BenjaminPrice/fvtt-docker#11]
### Description

I'm seeing this error in the logs for the fvtt container right after launch.
```
(node:9) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'app' of '_0x477210' as it is undefined.
    at initialize (/opt/foundryvtt/resources/app/dist/init.js:1:3590)
    at Object.<anonymous> (/opt/foundryvtt/resources/app/main.js:163:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To
 terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Archive:  foundryvtt-0.6.5.zip
unzip: can't read standard input
(node:9) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'app' of '_0x477210' as it is undefined.
    at initialize (/opt/foundryvtt/resources/app/dist/init.js:1:3590)
    at Object.<anonymous> (/opt/foundryvtt/resources/app/main.js:163:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To
 terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
replace LICENSE.electron.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: Archive:  foundryvtt-0.6.5.zip
unzip: can't read standard input
```

### Deployment information
I'm following the guide [here](https://benprice.dev/posts/fvtt-docker-tutorial/), with the following image for fvtt
```
direckthit/fvtt-docker   latest              88bed6c9f362        2 months ago        88.1MB
```

As you can see from the logs, I'm attempting to run it with `foundryvtt 0.6.5`.

My folder structure is outlined below (root at `/home/ryanliu6`:
```
|-- foundrydl
     |-- foundryvtt-0.6.5.zip
|-- foundrydata
|-- portainer
|-- traefik
```

I'm not sure what went wrong with my configuration or setup, and any help will be appreciated!

**Comment by mneis1** [comment]
I had the same issue. I solved it by changing the read/write access on my foundrydata directory. Try running`chmod 777 foundrydata`.

**Comment by RyanLiu6** [comment]
> 
> 
> I had the same issue. I solved it by changing the read/write access on my foundrydata directory. Try running`chmod 777 foundrydata`.

That seems to be the fix. I migrated from my pm2 + nginx setup to this and I had to run `chmod -R 777 foundrydata`.
